name: Copy Root Index to Posts

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy index.html to posts folder
        run: |
          mkdir -p posts
          cp index.html posts/index.html

      - name: Push changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add posts/index.html
          git commit -m "Automatically copy index.html to posts folder"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_PAT }}